import XCTest
@testable import SteamPigeon

/// Framing and message-CRC tests.
///
/// The framer runs before parsing and before authentication, on a byte stream that
/// BLE chops up arbitrarily. On iOS the chopping is *more* variable than on Android
/// because the MTU is negotiated after connect and cannot be pinned (ADR-0016), so
/// the same logical frame may arrive whole once and split the next time. These tests
/// drive the same bytes through every split that matters.
///
/// Ported from the Android `extractPackets` / `computeExpectedPacketLength` in
/// `BluetoothService.kt` (ADR-0009).
final class PacketFramerTests: XCTestCase {

    // MARK: - Helpers

    /// Build a well-formed frame of `totalSize` bytes with a valid message CRC.
    private func frame(_ type: MsgType, totalSize: Int, fill: (Int) -> Int = { $0 * 7 + 3 }) -> [UInt8] {
        var f = (0..<totalSize).map { UInt8(truncatingIfNeeded: fill($0)) }
        f[0] = WireProtocol.systemId
        f[1] = type.rawValue
        f[4] = 0
        f[5] = 0
        let crc = PacketFramer.computeCrc(f)
        f[4] = UInt8(truncatingIfNeeded: crc)
        f[5] = UInt8(truncatingIfNeeded: crc >> 8)
        return f
    }

    private func prelaunch() -> [UInt8] {
        frame(.preLaunchData, totalSize: WireProtocol.headerSize + WireProtocol.prelaunchMessagePayloadSize)
    }

    private func telemetry() -> [UInt8] {
        frame(.telemetryData, totalSize: WireProtocol.headerSize + WireProtocol.telemetryMessagePayloadSize,
              fill: { $0 * 5 + 11 })
    }

    // MARK: - Message CRC, pinned to the compiled firmware
    //
    // Generated by compiling the locator's own Crc16Update/Crc16Continue and
    // reproducing `Communication::ValidateCRC`'s computation (seed 0xFFFF, bytes
    // [0,4) then [6,len) — the crc field is skipped). As with the auth vectors,
    // this pins Swift to the firmware rather than to itself.

    func testMessageCrcMatchesCompiledFirmware() {
        var pre = (0..<147).map { UInt8(truncatingIfNeeded: $0 * 7 + 3) }
        pre[0] = 0x44; pre[1] = 5
        XCTAssertEqual(0x39f5, PacketFramer.computeCrc(pre))

        var tel = (0..<83).map { UInt8(truncatingIfNeeded: $0 * 5 + 11) }
        tel[0] = 0x44; tel[1] = 6
        XCTAssertEqual(0x87ef, PacketFramer.computeCrc(tel))

        var rx = (0..<30).map { UInt8(truncatingIfNeeded: $0 * 3 + 1) }
        rx[0] = 0x44; rx[1] = 16
        XCTAssertEqual(0x3384, PacketFramer.computeCrc(rx))
    }

    /// The crc field is excluded from its own computation, so whatever is sitting in
    /// bytes 4..5 cannot change the result.
    func testCrcFieldIsExcludedFromItsOwnComputation() {
        var a = (0..<83).map { UInt8(truncatingIfNeeded: $0 * 5 + 11) }
        a[0] = 0x44; a[1] = 6
        var b = a
        a[4] = 0x00; a[5] = 0x00
        b[4] = 0xAB; b[5] = 0xCD
        XCTAssertEqual(PacketFramer.computeCrc(a), PacketFramer.computeCrc(b))
    }

    // MARK: - Length

    func testFixedLengthTypes() {
        XCTAssertEqual(.known(147), PacketFramer.expectedPacketLength(prelaunch()))
        XCTAssertEqual(.known(83),  PacketFramer.expectedPacketLength(telemetry()))
        XCTAssertEqual(.known(30),  PacketFramer.expectedPacketLength(frame(.receiverInfo, totalSize: 30)))
        XCTAssertEqual(.known(84),  PacketFramer.expectedPacketLength(frame(.channelSurvey, totalSize: 84)))
        XCTAssertEqual(.known(66),  PacketFramer.expectedPacketLength(frame(.flightEvents, totalSize: 66)))
        XCTAssertEqual(.known(96),  PacketFramer.expectedPacketLength(frame(.flightMetadata, totalSize: 96)))
        XCTAssertEqual(.known(134), PacketFramer.expectedPacketLength(frame(.versionInfo, totalSize: 134)))
        XCTAssertEqual(.known(7),   PacketFramer.expectedPacketLength(frame(.deploymentTest, totalSize: 7)))
        XCTAssertEqual(.known(255), PacketFramer.expectedPacketLength(frame(.flightDataParity, totalSize: 255)))
    }

    func testShortBufferNeedsMoreBytes() {
        XCTAssertEqual(.needMoreBytes, PacketFramer.expectedPacketLength([0x44, 5, 0, 0, 0]))
    }

    /// `startup` is a real wire value the locator sends, and the app deliberately does
    /// not frame it — matching Android. Asserted so the choice is visible rather than
    /// looking like a missing case.
    func testStartupIsDeliberatelyUnframed() {
        XCTAssertNotNil(MsgType(rawValue: 0), "startup must still be a claimed wire value")
        XCTAssertEqual(.unframeable, PacketFramer.expectedPacketLength(frame(.startup, totalSize: 74)))
    }

    func testAppOriginatedTypesAreUnframeable() {
        for t in [MsgType.armRequest, .disarmRequest, .flightDataAck, .versionRequest,
                  .receiverInfoRequest, .channelSurveyRequest, .padAlertSnoozeRequest] {
            XCTAssertEqual(.unframeable, PacketFramer.expectedPacketLength(frame(t, totalSize: 20)),
                           "\(t) is app→device and should not be framed")
        }
    }

    func testUnknownMsgTypeIsUnframeable() {
        var f = [UInt8](repeating: 0, count: 20)
        f[0] = WireProtocol.systemId
        f[1] = 99                                    // not a MsgType
        XCTAssertEqual(.unframeable, PacketFramer.expectedPacketLength(f))
    }

    // MARK: - Variable-length FlightData

    private func flightDataFrame(packetIndex: Int, packetCount: Int, totalSamples: Int) -> [UInt8] {
        let o = WireProtocol.headerSize
        var header = [UInt8](repeating: 0, count: FlightDataSizes.flightDataHeaderSize)
        header[0] = WireProtocol.systemId
        header[1] = MsgType.flightData.rawValue
        header[o + 2] = UInt8(truncatingIfNeeded: packetIndex)
        header[o + 3] = UInt8(truncatingIfNeeded: packetIndex >> 8)
        header[o + 4] = UInt8(truncatingIfNeeded: packetCount)
        header[o + 5] = UInt8(truncatingIfNeeded: packetCount >> 8)
        header[o + 6] = UInt8(truncatingIfNeeded: totalSamples)
        header[o + 7] = UInt8(truncatingIfNeeded: totalSamples >> 8)
        header[o + 8] = UInt8(truncatingIfNeeded: totalSamples >> 16)
        header[o + 9] = UInt8(truncatingIfNeeded: totalSamples >> 24)
        return header
    }

    func testFullFlightDataPacketLength() {
        // 8 samples = header 16 + compressed header 48 + 7 deltas × 24 = 232
        let h = flightDataFrame(packetIndex: 0, packetCount: 4, totalSamples: 32)
        XCTAssertEqual(.known(232), PacketFramer.expectedPacketLength(h))
    }

    func testFinalShortFlightDataPacketLength() {
        // 25 total samples, packet 3 covers samples 24..: only 1 sample → 16 + 48 = 64
        let h = flightDataFrame(packetIndex: 3, packetCount: 4, totalSamples: 25)
        XCTAssertEqual(.known(64), PacketFramer.expectedPacketLength(h))
    }

    /// packet_count == 0 is the locator's "no data for this record" marker: a
    /// header-only frame. Framing it as anything longer stalls the transfer.
    func testEmptyRecordMarkerIsHeaderOnly() {
        let h = flightDataFrame(packetIndex: 0, packetCount: 0, totalSamples: 0)
        XCTAssertEqual(.known(FlightDataSizes.flightDataHeaderSize), PacketFramer.expectedPacketLength(h))
    }

    /// A partial FlightData header must wait, not resync — the length lives inside it.
    func testPartialFlightDataHeaderWaits() {
        let h = Array(flightDataFrame(packetIndex: 0, packetCount: 4, totalSamples: 32).prefix(12))
        XCTAssertEqual(.needMoreBytes, PacketFramer.expectedPacketLength(h))
    }

    // MARK: - Reassembly

    func testSingleWholeFrame() {
        var f = PacketFramer()
        let out = f.append(prelaunch())
        XCTAssertEqual(1, out.count)
        XCTAssertEqual(prelaunch(), out.first)
        XCTAssertTrue(f.buffer.isEmpty)
    }

    func testTwoConcatenatedFramesInOneNotification() {
        var f = PacketFramer()
        let out = f.append(prelaunch() + telemetry())
        XCTAssertEqual(2, out.count)
        XCTAssertEqual(prelaunch(), out[0])
        XCTAssertEqual(telemetry(), out[1])
        XCTAssertTrue(f.buffer.isEmpty)
    }

    /// The case iOS makes likely: one frame split across notifications.
    func testFrameSplitAcrossTwoNotifications() {
        let whole = prelaunch()
        var f = PacketFramer()
        XCTAssertTrue(f.append(whole[0..<60]).isEmpty, "must not emit a partial frame")
        let out = f.append(whole[60...])
        XCTAssertEqual([whole], out)
    }

    /// The pathological split: one byte at a time. Exactly one frame must emerge, on
    /// the final byte and not before.
    func testFrameDeliveredOneByteAtATime() {
        let whole = telemetry()
        var f = PacketFramer()
        var emitted: [[UInt8]] = []
        for (i, byte) in whole.enumerated() {
            let out = f.append([byte])
            if i < whole.count - 1 {
                XCTAssertTrue(out.isEmpty, "emitted early at byte \(i)")
            }
            emitted += out
        }
        XCTAssertEqual([whole], emitted)
    }

    /// A 140-byte notification carrying a 147-byte frame plus the start of the next —
    /// the shape the hardware probe actually measured.
    func testRealisticNotificationChunking() {
        let stream = prelaunch() + telemetry() + prelaunch()
        var f = PacketFramer()
        var emitted: [[UInt8]] = []
        for chunk in stride(from: 0, to: stream.count, by: 140) {
            emitted += f.append(stream[chunk..<min(chunk + 140, stream.count)])
        }
        XCTAssertEqual([prelaunch(), telemetry(), prelaunch()], emitted)
        XCTAssertTrue(f.buffer.isEmpty)
    }

    // MARK: - Resync

    func testLeadingGarbageIsSkipped() {
        var f = PacketFramer()
        let out = f.append([0x00, 0x11, 0x22, 0xFF] + prelaunch())
        XCTAssertEqual([prelaunch()], out)
    }

    func testBadCrcFrameIsDroppedAndStreamResyncs() {
        var corrupt = prelaunch()
        corrupt[80] = corrupt[80] &+ 1              // inside the frame, CRC now wrong
        var f = PacketFramer()
        let out = f.append(corrupt + telemetry())
        XCTAssertEqual([telemetry()], out, "the good frame after a bad one must still arrive")
        XCTAssertEqual(1, f.badFrameCount)
    }

    /// A byte that merely looks like a system id mid-stream must not derail the
    /// following real frame.
    func testFalseSystemIdByteDoesNotSwallowTheNextFrame() {
        var f = PacketFramer()
        let out = f.append([WireProtocol.systemId, 0x63, 0x00] + telemetry())
        XCTAssertEqual([telemetry()], out)
    }

    func testResetDropsAPartialFrame() {
        let whole = prelaunch()
        var f = PacketFramer()
        _ = f.append(whole[0..<60])
        XCTAssertFalse(f.buffer.isEmpty)
        f.reset()
        XCTAssertTrue(f.buffer.isEmpty)
        // Bytes from a new connection must not complete the old half-frame.
        let out = f.append(whole[60...])
        XCTAssertTrue(out.isEmpty)
    }

    // MARK: - Reject capture

    /// A bad-CRC count on its own cannot be explained after the fact. The bytes can.
    func testRejectedFrameIsCapturedWithEnoughToIdentifyIt() {
        var corrupt = prelaunch()
        corrupt[80] = corrupt[80] &+ 1
        var f = PacketFramer()
        _ = f.append(corrupt + telemetry())

        XCTAssertEqual(1, f.recentRejects.count)
        let r = f.recentRejects[0]
        XCTAssertEqual(MsgType.preLaunchData.rawValue, r.msgTypeByte)
        XCTAssertEqual(147, r.claimedLength)
        XCTAssertEqual(WireProtocol.systemId, r.head.first)
        XCTAssertTrue(r.summary.contains("preLaunchData"), r.summary)
        XCTAssertTrue(r.summary.contains("147"), r.summary)
    }

    /// The capture is a diagnostic, not a log — it must not grow without bound.
    func testRejectCaptureIsCapped() {
        var f = PacketFramer()
        for _ in 0..<40 {
            var corrupt = telemetry()
            corrupt[40] = corrupt[40] &+ 1
            _ = f.append(corrupt)
        }
        XCTAssertGreaterThan(f.badFrameCount, 12)
        XCTAssertLessThanOrEqual(f.recentRejects.count, 12)
    }

    /// A Startup message is relayed to the app but not framed. Confirmed on the bench
    /// that it does NOT explain bad-CRC counts: walking it costs nothing, because the
    /// resync path discards non-system-id bytes without counting them.
    func testStartupMessageDoesNotProduceBadCrcCounts() {
        var startup = [UInt8](repeating: 0, count: 74)
        startup[0] = WireProtocol.systemId
        startup[1] = MsgType.startup.rawValue
        for i in 10..<74 { startup[i] = UInt8(truncatingIfNeeded: 0x41 + (i % 26)) }  // ASCII version
        let crc = PacketFramer.computeCrc(startup)
        startup[4] = UInt8(truncatingIfNeeded: crc)
        startup[5] = UInt8(truncatingIfNeeded: crc >> 8)

        var f = PacketFramer()
        let out = f.append(startup + telemetry())
        XCTAssertEqual(0, f.badFrameCount, "startup must not pollute the bad-frame signal")
        XCTAssertEqual([telemetry()], out, "the frame behind it must still arrive")
    }

    /// The buffer must not grow without bound when the stream is pure noise.
    func testGarbageOnlyStreamDoesNotAccumulate() {
        var f = PacketFramer()
        let out = f.append([UInt8](repeating: 0x00, count: 1000))
        XCTAssertTrue(out.isEmpty)
        XCTAssertLessThan(f.buffer.count, WireProtocol.headerSize,
                          "non-system-id bytes must be consumed, not hoarded")
    }
}
